### ISSUE TITLE
你好，花的分类数据在哪里下载呢

### ISSUE THREAD

**Issue by 19chang19** [lilei1128/pytorch-image-classification#1]
你好，花的分类数据在哪里下载呢

**Comment by lilei1128** [comment]
input_data.rar 就是数据集的压缩文件。

**Comment by lilei1128** [comment]
项目中的input_data.rar就是数据集压缩包。



---原始邮件---
发件人: "19chang19"<notifications@github.com&gt;
发送时间: 2020年2月1日(周六) 晚上10:29
收件人: "lilei1128/pytorch-image-classification"<pytorch-image-classification@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [lilei1128/pytorch-image-classification] 你好，花的分类数据在哪里下载呢 (#1)



你好，花的分类数据在哪里下载呢

**Comment by 19chang19** [comment]
看到了，谢谢.....
